server:
  port: 8200
  cors: http://localhost:8080
spring:
  profiles:
    active: local
  application:
    name: sigpoauth
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sigip-1
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
jasperserver:
  username: jasperadmin
  password: jasperadmin
logging:
  file: logs/${spring.application.name}.log
