server:
  port: 8200
  cors: http://10.52.5.77:8080
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/sigip.p12
    key-store-password: rolando1234
    key-alias: sigip
    enabled: false
spring:
  profiles:
    active: dev
  application:
    name: sigpoauth
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sigipMarzo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
jasperserver:
  username: jasperadmin
  password: jasperadmin
logging:
  file: logs/${spring.application.name}.log
