server:
  port: 8200
  cors: http://172.16.2.52:8081
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/sigip.p12
    key-store-password: rolando1234
    key-alias: sigip
    enabled: true
spring:
  profiles:
    active: prod
  application:
    name: sigpoauth
  datasource:
    url: jdbc:postgresql://172.16.2.52:5432/sigip
    username: postgres
    password: postgres1234
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
jasperserver:
  username: jasperadmin
  password: jasperadmin
logging:
  file: logs/${spring.application.name}.log
